apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jy0cl3992-java-springboot 
  janus-idp.io/tekton: jy0cl3992-java-springboot
  backstage.io/kubernetes-id: jy0cl3992-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jy0cl3992-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml